#!/usr/bin/env python3
"""Generate osiris.reflect registration from CLASS/PROPERTY-marked headers.

Parses a header with libclang (with OSIRIS_CODEGEN defined so the markers become
clang annotations), then emits a .reflect.gen.cpp that specializes type_of<T>() and
registers the type. This is the automated equivalent of the OSIRIS_REFLECT_TYPE macro.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import clang.cindex as cx
except ImportError:
    sys.exit("error: python 'libclang' not found. Install with: pip install libclang")

PROPERTY_TAG = "osiris.property"


def has_annotation(cursor, tag: str) -> bool:
    return any(
        c.kind == cx.CursorKind.ANNOTATE_ATTR and c.spelling == tag
        for c in cursor.get_children()
    )


def qualified_name(cursor) -> str:
    parts = []
    node = cursor
    while node is not None and node.kind != cx.CursorKind.TRANSLATION_UNIT:
        if node.spelling:
            parts.append(node.spelling)
        node = node.semantic_parent
    return "::".join(reversed(parts))


def reflected_types(tu, source: Path):
    source = source.resolve()
    for cursor in tu.cursor.walk_preorder():
        if cursor.kind not in (cx.CursorKind.STRUCT_DECL, cx.CursorKind.CLASS_DECL):
            continue
        if not cursor.is_definition():
            continue
        file = cursor.location.file
        if file is None or Path(file.name).resolve() != source:
            continue
        fields = [
            (field.spelling, field.type.spelling)
            for field in cursor.get_children()
            if field.kind == cx.CursorKind.FIELD_DECL and has_annotation(field, PROPERTY_TAG)
        ]
        # A type is reflected if it has at least one PROPERTY() field.
        if fields:
            yield qualified_name(cursor), fields


def generate(types, include: str) -> str:
    out = [
        "// AUTO-GENERATED by reflect-codegen. Do not edit.",
        f'#include "{include}"',
        "",
        '#include "osiris/reflect/registry.hpp"',
        '#include "osiris/reflect/type_info.hpp"',
        "",
        "#include <cstddef>",
        "",
    ]
    for qname, fields in types:
        var = "k_reg_" + qname.replace("::", "_")
        out.append("template <>")
        out.append(f"const ::osiris::reflect::TypeInfo& ::osiris::reflect::TypeOf<{qname}>()")
        out.append("{")
        out.append("    static constexpr ::osiris::reflect::FieldInfo k_fields[] = {")
        for name, type_name in fields:
            out.append(
                f'        {{"{name}", "{type_name}", '
                f"offsetof({qname}, {name}), sizeof({type_name})}},"
            )
        out.append("    };")
        out.append(
            f'    static const ::osiris::reflect::TypeInfo k_info{{"{qname}", '
            f"sizeof({qname}), alignof({qname}), k_fields}};"
        )
        out.append("    return k_info;")
        out.append("}")
        out.append(
            f"static const ::osiris::reflect::detail::AutoRegister {var}"
            f"{{::osiris::reflect::TypeOf<{qname}>()}};"
        )
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", type=Path, help="write here instead of stdout")
    parser.add_argument("--include", help="path emitted in the generated #include (default: input name)")
    parser.add_argument("-I", dest="includes", action="append", default=[], help="header search dir")
    parser.add_argument("--std", default="c++20")
    parser.add_argument("--libclang", help="path to libclang.dll if not auto-detected")
    args = parser.parse_args()

    if args.libclang:
        cx.Config.set_library_file(args.libclang)

    clang_args = [f"-std={args.std}", "-x", "c++", "-DOSIRIS_CODEGEN"]
    clang_args += [f"-I{inc}" for inc in args.includes]

    tu = cx.Index.create().parse(str(args.input), args=clang_args)

    for diag in tu.diagnostics:
        if diag.severity >= cx.Diagnostic.Error:
            print(f"clang: {diag.spelling}", file=sys.stderr)

    types = list(reflected_types(tu, args.input))
    code = generate(types, args.include or args.input.name)

    if args.output:
        args.output.write_text(code, encoding="utf-8")
        print(f"generated {args.output} ({len(types)} type(s))")
    else:
        print(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
